[package]
name = "terraphim_test_utils"
version.workspace = true
edition.workspace = true
description = "Shared test utilities for Terraphim crates"
license = "MIT"

[dependencies]

[build-dependencies]
rustc_version = "0.4"
