server_hostname = '127.0.0.1:8000'
api_endpoint = 'http://localhost:8000/api'
initialized = true
default_data_path = '/tmp/terraphim_test'
[profiles.s3]
access_key_id = 'test_key'
region = 'us-west-1'
endpoint = 'http://rpi4node3:8333/'
type = 's3'
bucket = 'test'
secret_access_key = 'test_secret'

[profiles.sled]
type = 'sled'
datadir = '/tmp/opendal/sled'

[profiles.dash]
root = '/tmp/dashmaptest'
type = 'dashmap'

[profiles.rock]
datadir = '/tmp/opendal/rocksdb'
type = 'rocksdb'
