server_hostname = '127.0.0.1:8000'
api_endpoint = 'http://localhost:8000/api'
initialized = true
default_data_path = '/tmp/terraphim_test'
[profiles.s3]
secret_access_key = 'test_secret'
bucket = 'test'
access_key_id = 'test_key'
endpoint = 'http://rpi4node3:8333/'
type = 's3'
region = 'us-west-1'

[profiles.rock]
datadir = '/tmp/opendal/rocksdb'
type = 'rocksdb'

[profiles.rocksdb]
type = 'rocksdb'
datadir = '/tmp/opendal/rocksdb_test'

[profiles.dash]
type = 'dashmap'
root = '/tmp/dashmaptest'

[profiles.sled]
type = 'sled'
datadir = '/tmp/opendal/sled'
