[package]
name = "terraphim_settings"
version = "0.1.0"
edition = "2021"
authors = ["Terraphim Contributors"]
description = "Terraphim settings handling library"
documentation = "https://terraphim.ai"
homepage = "https://terraphim.ai"
repository = "https://github.com/terraphim/terraphim-ai"
keywords = ["personal-assistant", "ai", "privacy", "settings", "configuration"]
license = "Apache-2.0"
readme = "../../README.md"

[dependencies]
directories = "5.0.1"
log = "0.4.14"
thiserror = "2.0.16"
twelf = { version = "0.15.0", features = ["json", "toml", "env", "clap"] }
serde = { version = "1.0.182", features = ["derive"] }

[dev-dependencies]
tempfile="3.2.0"
envtestkit = "1.1.2"
test-log = "0.2.14"
